services:
  web:
    build: .
    ports:
      - "8081:3000"
    volumes:
      - .:/src/app
      - ./storages/uploads:/src/app/storages/uploads:rw
      - ./storages/logs:/src/app/storages/logs:rw
    env_file:
      - .env