services:
  app:
    build: .
    container_name: cloud-storages-app
    volumes:
      - ./storages/logs:/app/storages/logs
      - ./storages/uploads:/app/storages/uploads
    ports:
      - "8081:3000"
    env_file:
      - .env

volumes:
  logs:
  uploads:
